name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/apps/sh/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/apps/sh/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test bash scripts
      run: sh test-scripts.sh
